# Generated by Django 3.1.3 on 2020-11-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
